apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff_books
  namespace: book-store-ns
spec:
  selector:
    matchLabels:
      run: bff_books
  replicas: 1
  template:
    metadata:
      labels:
        run: bff_books
    spec:
      containers:
      - name: bff_books_container
        image: vkaulagi/bff_books
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /status
            port: 80
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3