apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-customers-deploy
  namespace: book-store-ns
  labels:
    serviceName: bff-customers
spec:
  selector:
    matchLabels:
      serviceName: bff-customers
  replicas: 1
  template:
    metadata:
      labels:
        serviceName: bff-customers
    spec:
      containers:
      - name: bff-customers-container
        image: vkaulagi/bff_customers
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /status
            port: 80
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3