apiVersion: v1
kind: Service
metadata:
  name: bff-books
  namespace: book-store-ns
  labels:
    run: bff-books
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: bff-books
    # type: LoadBalancer
  type: LoadBalancer
