apiVersion: v1
kind: Service
metadata:
  name: bff-customers
  namespace: book-store-ns
  labels:
    run: bff-customers
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: bff-customers
    type: LoadBalancer