apiVersion: v1
kind: Service
metadata:
  name: books
  namespace: book-store-ns
  labels:
    run: books
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 8000
  type: LoadBalancer
  selector:
    run: books
    # type: LoadBalancer