apiVersion: v1
kind: Service
metadata:
  name: books-service
  namespace: book-store-ns
  # labels:
  #   run: books
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    serviceName: books
  type: LoadBalancer
