apiVersion: v1
kind: Service
metadata:
  name: crm-service
  namespace: book-store-ns
  # labels:
  #   run: books
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 8080
  selector:
    serviceName: crm
  type: LoadBalancer
