apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-deploy
  namespace: book-store-ns
  labels:
    serviceName: crm
spec:
  selector:
    matchLabels:
      serviceName: crm
  replicas: 1
  template:
    metadata:
      labels:
        serviceName: crm
    spec:
      containers:
      - name: crm-container
        image: vkaulagi/crm
        ports:
        - containerPort: 3000
          # initialDelaySeconds: 30
          # periodSeconds: 10
          # timeoutSeconds: 5
          # successThreshold: 1
          # failureThreshold: 3