apiVersion: v1
kind: Service
metadata:
  name: customers-service
  namespace: book-store-ns
  # labels:
  #   run: customers
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    serviceName: customers
    # type: LoadBalancer
  type: LoadBalancer