apiVersion: v1
kind: Service
metadata:
  name: customers
  namespace: book-store-ns
  labels:
    run: customers
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 8000
  type: LoadBalancer
  selector:
    run: customers
    # type: LoadBalancer