apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-deploy
  namespace: book-store-ns
  labels:
    serviceName: books
spec:
  selector:
    matchLabels:
      serviceName: customers
  replicas: 1
  template:
    metadata:
      labels:
        serviceName: customers
    spec:
      containers:
      - name: customers-container
        image: vkaulagi/customers
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /status
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3